// <auto-generated />
using System;
using HospitalSystemTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalSystemTask.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20250825145247_o-oWardNurse")]
    partial class ooWardNurse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalSystemTask.Models.Consultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Consultants");
                });

            modelBuilder.Entity("HospitalSystemTask.Models.Drug", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("HospitalSystemTask.Models.Drug_Brand", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Code", "Brand");

                    b.ToTable("Drug_Brands");
                });

            modelBuilder.Entity("HospitalSystemTask.Models.Nurse", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Word_Id")
                        .HasColumnType("int");

                    b.HasKey("Number");

                    b.ToTable("Nurses");
                });

            modelBuilder.Entity("HospitalSystemTask.Models.Nurse_Drug_Patient", b =>
                {
                    b.Property<int>("Pat_Id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Drug_Code")
                        .HasColumnType("int");

                    b.Property<int>("Nur_Num")
                        .HasColumnType("int");

                    b.HasKey("Pat_Id", "Date", "Time");

                    b.ToTable("nurse_Drug_Patients");
                });

            modelBuilder.Entity("HospitalSystemTask.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedId")
                        .HasColumnType("int");

                    b.Property<int>("Con_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Ward_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedId");

                    b.HasIndex("HostsId");

                    b.HasIndex("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HospitalSystemTask.Models.Patient_Con", b =>
                {
                    b.Property<int>("Con_Id")
                        .HasColumnType("int");

                    b.Property<int>("Pat_Id")
                        .HasColumnType("int");

                    b.HasKey("Con_Id", "Pat_Id");

                    b.ToTable("Patient_Cons");
                });

            modelBuilder.Entity("HospitalSystemTask.Models.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Nurse_Num")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nurse_Num")
                        .IsUnique();

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("HospitalSystemTask.Models.Patient", b =>
                {
                    b.HasOne("HospitalSystemTask.Models.Consultant", "Assigned")
                        .WithMany()
                        .HasForeignKey("AssignedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSystemTask.Models.Ward", "Hosts")
                        .WithMany()
                        .HasForeignKey("HostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSystemTask.Models.Patient", null)
                        .WithMany("Patients")
                        .HasForeignKey("PatientId");

                    b.Navigation("Assigned");

                    b.Navigation("Hosts");
                });

            modelBuilder.Entity("HospitalSystemTask.Models.Ward", b =>
                {
                    b.HasOne("HospitalSystemTask.Models.Nurse", "Supervisor")
                        .WithOne("SupervisedWard")
                        .HasForeignKey("HospitalSystemTask.Models.Ward", "Nurse_Num")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("HospitalSystemTask.Models.Nurse", b =>
                {
                    b.Navigation("SupervisedWard");
                });

            modelBuilder.Entity("HospitalSystemTask.Models.Patient", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
